use_frameworks!
inhibit_all_warnings!

platform :ios, '13.0'

target 'macaroon_Example' do
  pod 'Macaroon/Banner',  :path => '../'
  pod 'Macaroon/Biometrics',  :path => '../'
  pod 'Macaroon/Core',  :path => '../'
  pod 'Macaroon/Core-Hipo',  :path => '../'
  pod 'Macaroon/CustomUI/FloatingPlaceholderTextInputs',  :path => '../'
  pod 'Macaroon/Form', :path => '../'
  pod 'Macaroon/MediaPicker', :path => '../'
  pod 'Macaroon/Mixpanel', :path => '../'
  pod 'Macaroon/PushNotification', :path => '../'
  pod 'Macaroon/SwiftLint',  :path => '../'
  pod 'Macaroon/SVGImage', :path => '../'
  pod 'Macaroon/TabBar', :path => '../'
  pod 'Macaroon/Zendesk-Chat', :path => '../'

  target 'macaroon_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
   end
  installer.aggregate_targets.each do |target|
    target.xcconfigs.each do |variant, xcconfig|
      xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
      IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
    end
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
        xcconfig_path = config.base_configuration_reference.real_path
        IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
    end
  end
end
